# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.0.7
_src_path: https://github.com/jupyterlab/extension-template
author_email: ''
author_name: Denisa
has_binder: false
has_settings: false
kind: frontend
labextension_name: jupyterlab-ext-example
project_short_description: A JupyterLab extension example.
python_name: jupyterlab_ext_example
repository: ''
test: false

